//Arturo Alejandro Guzman Perez 22110356
//Cesar Eduardo Campos Virgen 22110354

bin/proyecto.exe : src/main.cpp 
//objetivo : dependencias 
	//tarea
	g++ -o/proyecto src/main.cpp -Iinclude

run: bin/proyecto.exe
	./bin/proyecto.exe

clean: bin/proyecto.exe
	rm -f bin/*.exev   